apiVersion: v1
kind: PhJob
metadata:
  name: a
  description: "pharbers job description"
  labels:
    name: a
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    code: phmain.py
    config: phconf.yaml
    args:
      - key: a
        value: 123
      - key: b
        value: 456
    outputs:
      - key: c
        value: abc
      - key: d
        value: def



