apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf-20200826.yaml
    args:
      - key: a
        value: 123
      - key: b
        value: 456
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789


