apiVersion: v1
kind: PhDag
metadata:
  name: $name
  description: "pharbers job description"
  labels:
    name: $name
spec:
  description: "A Max Auto Job Example"
  start_date: 1 # if you don't understand, don't touch it
  schedule_interval: "None" # if you don't understand, don't touch it
  dag_timeout: 60 # minutes
  email: ['airflow@example.com']
  email_on_failure: False
  email_on_retry: False
  retries: 1
  retry_delay: "minutes=5"
  owner: phcli_defalut
  dag_id: $name
  dag_tag: $name
  jobs:
    - name: group.test1
      runtime: $runtime
      command: $command
    - name: group.test2
      runtime: $runtime
      command: $command
  linkage:
    - "group.test1 >> group.test2"
