apiVersion: v1
kind: PhJob
metadata:
  name: test_a
  description: "pharbers job description"
  labels:
    name: test_a
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 10.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: a
        value: 'abc'
      - key: b
        value: 'abc'
    outputs:
      - key: c
        value: 'abc'
      - key: d
        value: 'abc'



